language: node_js

env:
  - HAPI_VERSION="19"
  - HAPI_VERSION="20"

node_js:
  - "12"
  - "14"
  - "node"

install:
  - "npm install"
  - "npm install @hapi/hapi@$HAPI_VERSION"

after_script: "npm run coveralls"
